// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.
/*
package frc.robot.subsystems.LEDs;

import edu.wpi.first.wpilibj.motorcontrol.Spark;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

public class LEDSignals extends SubsystemBase {
    public static final Spark signalLED = LEDSignalCfg.SIGNAL_LED;

  public LEDSignals() {}

  @Override
  public void periodic() {
    // This method will be called once per scheduler run
  }

  public static void hopperInColor(){
    signalLED.set(0.67); //Gold
  }

  public static void hopperOutColor(){
    signalLED.set(0.87); //Blue violet
  }

  public static void intakeOnOutColor(){
    signalLED.set(-0.09); //Blinking Blue Violet
  }

  public static void intakeOnInColor(){
    signalLED.set(-0.07); //Blinking Gold
  }

  public static void resetLEDs(){
    signalLED.set(2145); 
  }
}
*/
/* Generated by Phoenix Tuner X */
package frc.robot.subsystems.LEDs;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.ColorFlowAnimation;
import com.ctre.phoenix6.controls.FireAnimation;
import com.ctre.phoenix6.controls.LarsonAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.LarsonBounceValue;
import com.ctre.phoenix6.signals.RGBWColor;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LEDSignals extends SubsystemBase {
    
    private final CANBus kCANBus = new CANBus("rio");
    private final CANdle m_candle = new CANdle(14, kCANBus);

    private final ColorFlowAnimation m_slot0Animation = new ColorFlowAnimation(0, 7)
        .withSlot(0)
        .withColor(new RGBWColor(19, 9, 255, 0))
        .withDirection(AnimationDirectionValue.Forward)
        .withFrameRate(Hertz.of(25));
    
    private final FireAnimation firingAnimation = new FireAnimation(8, 22)
        .withSlot(1)
        .withBrightness(0.411)
        .withDirection(AnimationDirectionValue.Forward)
        .withSparking(0.712)
        .withCooling(0.127)
        .withFrameRate(Hertz.of(20.58));

    private final LarsonAnimation intakeOnAnimation = new LarsonAnimation(8, 22)
        .withSlot(1)
        .withColor(new RGBWColor(47, 255, 2, 0))
        .withSize(5)
        .withBounceMode(LarsonBounceValue.Front)
        .withFrameRate(Hertz.of(27.93));

    public static void hopperInColor(){
      
  }

    public static void hopperOutColor(){
    
  }

    public static void intakeOnOutColor(){
    
  }

    public static void intakeOnInColor(){
    
  }

    private final SolidColor[] m_colors = new SolidColor[] {
    };

    public LEDSignals() {
        setDefaultCommand(updateLEDs());
    }

    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
            for (var solidColor : m_colors) {
                m_candle.setControl(solidColor);
            }
            m_candle.setControl(m_slot0Animation);
            if //put some logic here to detirmine led state and set control to correct animation
        }).ignoringDisable(true);
    }
}
